# Generated by Django 3.2.9 on 2021-12-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Pending'), (2, 'Resolved')], default='UTC', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.client')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.operator')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.store')),
            ],
        ),
    ]
