# Generated by Django 3.2.9 on 2021-12-04 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Resolved')], default=1),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Sent')], default=1)),
                ('payload', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Text contains invalid chartacter', regex='[a-zA-Z0-9{}$%_-\\/~@#$%^&()!?]')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.conversation')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.discount')),
            ],
        ),
    ]
