# Generated by Django 3.2.9 on 2021-12-05 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_alter_chat_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^\\+?(?:[0-9]?){6,14}$')]),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^\\+?(?:[0-9]?){6,14}$')]),
        ),
    ]
